name: CI

on:
  - push
  - workflow_dispatch

permissions:
  contents: read

jobs:
  test:
    name: Check icon layers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          enable-cache: true

      - name: Run extract layers script
        run: ./scripts/extract_layers.py

      - name: Check for changes
        uses: tj-actions/verify-changed-files@a1c6acee9df209257a246f2cc6ae8cb6581c1edf # v20.0.4
        with:
          fail-if-changed: true
